CREATE TABLE DUENO (
IDDueno INT(12) PRIMARY KEY,
Nombre VARCHAR(30) NOT NULL,
Telefono VARCHAR(30) NOT NULL,
Direccion VARCHAR(50),
Mail VARCHAR (50)
)

CREATE TABLE VETERINARIO (
IDVeterinario INT(12) PRIMARY KEY,
Nombre VARCHAR(30) NOT NULL,
Telefono VARCHAR(30) NOT NULL,
Especialidad VARCHAR(50)
)

CREATE TABLE MASCOTA (
MascotaID INT(12) AUTO_INCREMENT PRIMARY KEY,
Nombre VARCHAR(30) NOT NULL,
Foto VARCHAR(30) NOT NULL,
Tipo VARCHAR(50),
FechaNacimiento DATE,
DuenoID INT(12),
FOREIGN KEY (DuenoID) REFERENCES DUENO(IDDueno)
)

CREATE TABLE CITA (
IDCita INT(12) AUTO_INCREMENT PRIMARY KEY,
Fecha DATE NOT NULL,
IDMascota INT(12) NOT NULL,
Proposito VARCHAR(50),
Valor DATE,
IDVeterinario INT(12) NOT NULL,
FOREIGN KEY (IDMascota) REFERENCES MASCOTA(MascotaID),
FOREIGN KEY (IDVeterinario) REFERENCES VETERINARIO(IDVeterinario)
)

CREATE TABLE MEDICAMENTO (
IDMedicamento INT(12) AUTO_INCREMENT PRIMARY KEY,
Nombre VARCHAR(30) NOT NULL,
Precio INT(12) NOT NULL
)

CREATE TABLE RECETA (
IDReceta INT(12) AUTO_INCREMENT PRIMARY KEY,
IDCita INT(12) NOT NULL,
IDMedicamento INT(12) NOT NULL,
Precio INT(12),
Dosis VARCHAR(MAX),
FOREIGN KEY (IDCita) REFERENCES CITA(IDCita),
FOREIGN KEY (IDMedicamento) REFERENCES MEDICAMENTO(IDMedicamento)
)